[package]
name = "ai-trading-desktop"
version = "0.1.0"
description = "AI Trading Desktop桌面客户端"
authors = ["roberts9012062"]
edition = "2021"

[lib]
name = "ai_trading_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-http = { version = "2", features = [] }
tauri-plugin-updater = { version = "2", features = [] }
tauri-plugin-process = { version = "2", features = [] }
tauri-plugin-log = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
ring = "0.17"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["sync", "rt-multi-thread", "time"] }
time = { version = "0.3", features = ["formatting"] }
zeroize = "1"
tauri-plugin-shell = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-single-instance = "2.5.2"
