/** 厂商图标匹配规则（品牌关键词 → 图标/主题色） */

export interface BrandRule {
  brand: string
  test: RegExp
  src: string
  bg: string
  line: string
  shortName: string
}

/** 按 model_id / provider / display_name 匹配厂商；首条命中生效 */
export const BRAND_RULES: BrandRule[] = [
  {
    brand: "openai",
    test: /(gpt|o1|o3|o4|openai|chatgpt)/i,
    src: "/ai-icons/openai.png",
    bg: "#10a37f",
    line: "#10a37f",
    shortName: "OpenAI",
  },
  {
    brand: "anthropic",
    test: /(claude|anthropic|sonnet|opus|haiku)/i,
    src: "/ai-icons/claude.png",
    bg: "#d4a27f",
    line: "#c48a5a",
    shortName: "Claude",
  },
  {
    brand: "deepseek",
    test: /deepseek/i,
    src: "/ai-icons/deepseek.png",
    bg: "#4d6bfe",
    line: "#4d6bfe",
    shortName: "DeepSeek",
  },
  {
    brand: "gemini",
    test: /(gemini|google)/i,
    src: "/ai-icons/gemini.png",
    bg: "#4285f4",
    line: "#8ab4f8",
    shortName: "Gemini",
  },
  {
    brand: "qwen",
    test: /(qwen|tongyi|dashscope|通义|千问|bailian|百炼)/i,
    src: "/ai-icons/qwen.png",
    bg: "#615ced",
    line: "#7c6cff",
    shortName: "Qwen",
  },
  {
    brand: "doubao",
    test: /(doubao|豆包|volcengine|火山)/i,
    src: "/ai-icons/doubao.png",
    bg: "#3b82f6",
    line: "#60a5fa",
    shortName: "豆包",
  },
  {
    brand: "hunyuan",
    test: /(hunyuan|混元|yuanbao|元宝)/i,
    src: "/ai-icons/hunyuan.png",
    bg: "#0f62fe",
    line: "#4589ff",
    shortName: "混元",
  },
  {
    brand: "moonshot",
    test: /(moonshot|kimi|月之暗面)/i,
    src: "/ai-icons/kimi.png",
    bg: "#1a1a1a",
    line: "#a3a3a3",
    shortName: "Kimi",
  },
  {
    brand: "zhipu",
    test: /(glm|zhipu|智谱|chatglm|qingyan|清言)/i,
    src: "/ai-icons/zhipu.png",
    bg: "#0f62fe",
    line: "#4589ff",
    shortName: "智谱",
  },
  {
    brand: "baichuan",
    test: /(baichuan|百川)/i,
    src: "/ai-icons/baichuan.png",
    bg: "#f59e0b",
    line: "#fbbf24",
    shortName: "百川",
  },
  {
    brand: "minimax",
    test: /(minimax|abab)/i,
    src: "/ai-icons/minimax.png",
    bg: "#ef4444",
    line: "#f87171",
    shortName: "MiniMax",
  },
  {
    brand: "stepfun",
    test: /(stepfun|step-?fun|阶跃)/i,
    src: "/ai-icons/stepfun.png",
    bg: "#8b5cf6",
    line: "#a78bfa",
    shortName: "阶跃",
  },
  {
    brand: "yi",
    test: /(零一万物|01\.ai|zeroone|\byi-?\d)/i,
    src: "/ai-icons/yi.png",
    bg: "#10b981",
    line: "#34d399",
    shortName: "Yi",
  },
  {
    brand: "spark",
    test: /(spark|星火|讯飞|iflytek)/i,
    src: "/ai-icons/spark.png",
    bg: "#e8742c",
    line: "#f97316",
    shortName: "星火",
  },
  {
    brand: "wenxin",
    test: /(wenxin|文心|ernie|百度|baidu)/i,
    src: "/ai-icons/wenxin.png",
    bg: "#2932e1",
    line: "#4a5cf2",
    shortName: "文心",
  },
  {
    brand: "sensenova",
    test: /(sensenova|商汤|日日新)/i,
    src: "/ai-icons/sensenova.png",
    bg: "#db2777",
    line: "#ec4899",
    shortName: "商汤",
  },
  {
    brand: "skywork",
    test: /(skywork|天工|昆仑)/i,
    src: "/ai-icons/skywork.png",
    bg: "#2563eb",
    line: "#3b82f6",
    shortName: "天工",
  },
  {
    brand: "siliconcloud",
    test: /(siliconcloud|硅基流动)/i,
    src: "/ai-icons/siliconcloud.png",
    bg: "#0891b2",
    line: "#06b6d4",
    shortName: "硅基流动",
  },
  {
    brand: "modelscope",
    test: /(modelscope|魔搭)/i,
    src: "/ai-icons/modelscope.png",
    bg: "#7c3aed",
    line: "#8b5cf6",
    shortName: "魔搭",
  },
  {
    brand: "coze",
    test: /(coze|扣子)/i,
    src: "/ai-icons/coze.png",
    bg: "#0ea5e9",
    line: "#38bdf8",
    shortName: "Coze",
  },
  {
    brand: "ai360",
    test: /(360|智脑)/i,
    src: "/ai-icons/ai360.png",
    bg: "#16a34a",
    line: "#22c55e",
    shortName: "360",
  },
  {
    brand: "grok",
    test: /(grok|xai)/i,
    src: "/ai-icons/grok.png",
    bg: "#111111",
    line: "#e5e5e5",
    shortName: "Grok",
  },
  {
    brand: "mistral",
    test: /mistral/i,
    src: "/providers/default.svg",
    bg: "#f97316",
    line: "#fb923c",
    shortName: "Mistral",
  },
  {
    brand: "perplexity",
    test: /perplexity/i,
    src: "/ai-icons/perplexity.png",
    bg: "#20808d",
    line: "#22b8cf",
    shortName: "Perplexity",
  },
  {
    brand: "copilot",
    test: /copilot/i,
    src: "/ai-icons/copilot.png",
    bg: "#0f62fe",
    line: "#4589ff",
    shortName: "Copilot",
  },
  {
    brand: "openrouter",
    test: /openrouter/i,
    src: "/ai-icons/openrouter.png",
    bg: "#6b7280",
    line: "#9ca3af",
    shortName: "OpenRouter",
  },
  {
    brand: "groq",
    test: /groq/i,
    src: "/ai-icons/groq.png",
    bg: "#f55036",
    line: "#f87171",
    shortName: "Groq",
  },
  {
    brand: "together",
    test: /(together\.?ai|together)/i,
    src: "/ai-icons/together.png",
    bg: "#0f172a",
    line: "#334155",
    shortName: "Together",
  },
  {
    brand: "typesafe",
    test: /(typesafe|jev)/i,
    src: "/providers/typesafe.svg",
    bg: "#0d9488",
    line: "#14b8a6",
    shortName: "TypeSafe",
  },
]
